[log.console]
enabled = true
level = "TRACE"
log_format = "default"

[server]
host = "127.0.0.1"
port = 8000
type = "grpc"

[metrics]
host = "127.0.0.1"
port = 8080

[proxy]
# http_url = "http proxy url"                   # Proxy all HTTP traffic via this proxy
# https_url = "https proxy url"                 # Proxy all HTTPS traffic via this proxy
idle_pool_connection_timeout = 90               # Timeout for idle pool connections (defaults to 90s)
bypass_proxy_urls = ["localhost", "local"]

[connectors]
adyen.base_url = "https://checkout-test.adyen.com/"
adyen.dispute_base_url = "https://ca-test.adyen.com/"
razorpay.base_url = "https://api.razorpay.com/"
razorpayv2.base_url = "https://api.razorpay.com/"
fiserv.base_url = "https://cert.api.fiservapps.com/"
elavon.base_url = "https://api.demo.convergepay.com/VirtualMerchantDemo/"
xendit.base_url = "https://api.xendit.co/"
checkout.base_url = "https://api.sandbox.checkout.com/"
authorizedotnet.base_url = "https://apitest.authorize.net/xml/v1/request.api"
phonepe.base_url = "https://api.phonepe.com/apis/hermes/"
cashfree.base_url = "https://sandbox.cashfree.com/"
